/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mycar;

import java.awt.Color;

/**
 *
 * @author Shellby 56
 */
public class adicionar extends javax.swing.JFrame {

    /**
     * Creates new form adicionar
     */
    
    String marca = "";
    String[] modelosAudi = {"A1", "A2", "A4", "A5", "A6", "A7", "A8", "Q2", "Q3", "Q4", "Q5", "Q7", "Q8", "TT", "R8", "e-tron GT", "Q8 e-tron"};
    //String[] modelosBMW = {"A1", "A2", "A4", "A5", "A6", "A7", "A8", "Q2", "Q3", "Q4", "Q5", "Q7", "Q8", "TT", "R8", "e-tron GT", "Q8 e-tron"};
    //String[] modelosFerrari = {"A1", "A2", "A4", "A5", "A6", "A7", "A8", "Q2", "Q3", "Q4", "Q5", "Q7", "Q8", "TT", "R8", "e-tron GT", "Q8 e-tron"};
    Color transparente = new Color(200, 200, 200, 150);
    
    int contador = 1;
    public adicionar() {
        initComponents();
        
        PAudi.setVisible(false);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Titulo = new javax.swing.JLabel();
        PAudi = new java.awt.Panel();
        ImagemAudi = new javax.swing.JLabel();
        BTNAvancarAudi = new javax.swing.JButton();
        BTNAnteriorAudi = new javax.swing.JButton();
        NomeAudi = new javax.swing.JLabel();
        ConcluirModelo = new javax.swing.JButton();
        BTNAudi = new javax.swing.JToggleButton();
        BTNHonda = new javax.swing.JToggleButton();
        BTNBmw = new javax.swing.JToggleButton();
        BTNFerrari = new javax.swing.JToggleButton();
        BTNFord = new javax.swing.JToggleButton();
        BTNPorsche = new javax.swing.JToggleButton();
        BTNToyota = new javax.swing.JToggleButton();
        BTNMercedes = new javax.swing.JToggleButton();
        BTNVolkswagen = new javax.swing.JToggleButton();
        BTNHyundai = new javax.swing.JToggleButton();
        jButton1 = new javax.swing.JButton();
        BTNOpel = new javax.swing.JToggleButton();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1920, 1080));
        setUndecorated(true);
        setSize(new java.awt.Dimension(1920, 1080));
        getContentPane().setLayout(null);

        Titulo.setBackground(javax.swing.UIManager.getDefaults().getColor("Actions.Yellow"));
        Titulo.setFont(new java.awt.Font("Verdana Pro Cond Black", 0, 75)); // NOI18N
        Titulo.setForeground(new java.awt.Color(255, 153, 0));
        Titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Titulo.setText("Escolha a marca");
        getContentPane().add(Titulo);
        Titulo.setBounds(90, 20, 1830, 140);

        PAudi.setBackground(transparente);
        PAudi.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        PAudi.setLayout(null);

        ImagemAudi.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ImagemAudi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MODELOS/audi/A1.png"))); // NOI18N
        PAudi.add(ImagemAudi);
        ImagemAudi.setBounds(0, 270, 1380, 250);

        BTNAvancarAudi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/seta-direita.png"))); // NOI18N
        BTNAvancarAudi.setContentAreaFilled(false);
        BTNAvancarAudi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNAvancarAudiActionPerformed(evt);
            }
        });
        PAudi.add(BTNAvancarAudi);
        BTNAvancarAudi.setBounds(1180, 80, 120, 130);

        BTNAnteriorAudi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/seta-esquerda.png"))); // NOI18N
        BTNAnteriorAudi.setContentAreaFilled(false);
        BTNAnteriorAudi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNAnteriorAudiActionPerformed(evt);
            }
        });
        PAudi.add(BTNAnteriorAudi);
        BTNAnteriorAudi.setBounds(90, 80, 120, 130);

        NomeAudi.setFont(new java.awt.Font("Verdana Pro Cond Black", 0, 48)); // NOI18N
        NomeAudi.setForeground(new java.awt.Color(255, 153, 0));
        NomeAudi.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        NomeAudi.setText("Audi A1");
        PAudi.add(NomeAudi);
        NomeAudi.setBounds(210, 100, 970, 80);

        ConcluirModelo.setFont(new java.awt.Font("Verdana Pro Cond Black", 0, 48)); // NOI18N
        ConcluirModelo.setForeground(new java.awt.Color(255, 153, 0));
        ConcluirModelo.setText("Confirmar");
        ConcluirModelo.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(255, 153, 0)));
        ConcluirModelo.setContentAreaFilled(false);
        ConcluirModelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConcluirModeloActionPerformed(evt);
            }
        });
        PAudi.add(ConcluirModelo);
        ConcluirModelo.setBounds(590, 600, 240, 70);

        getContentPane().add(PAudi);
        PAudi.setBounds(290, 240, 1420, 720);

        BTNAudi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/marcas/audi.png"))); // NOI18N
        BTNAudi.setBorderPainted(false);
        BTNAudi.setContentAreaFilled(false);
        BTNAudi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNAudiActionPerformed(evt);
            }
        });
        getContentPane().add(BTNAudi);
        BTNAudi.setBounds(400, 250, 220, 220);

        BTNHonda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/marcas/honda.png"))); // NOI18N
        BTNHonda.setBorderPainted(false);
        BTNHonda.setContentAreaFilled(false);
        BTNHonda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNHondaActionPerformed(evt);
            }
        });
        getContentPane().add(BTNHonda);
        BTNHonda.setBounds(1410, 250, 220, 220);

        BTNBmw.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/marcas/bmw.png"))); // NOI18N
        BTNBmw.setBorderPainted(false);
        BTNBmw.setContentAreaFilled(false);
        BTNBmw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNBmwActionPerformed(evt);
            }
        });
        getContentPane().add(BTNBmw);
        BTNBmw.setBounds(660, 250, 220, 220);

        BTNFerrari.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/marcas/ferrari.png"))); // NOI18N
        BTNFerrari.setBorderPainted(false);
        BTNFerrari.setContentAreaFilled(false);
        BTNFerrari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNFerrariActionPerformed(evt);
            }
        });
        getContentPane().add(BTNFerrari);
        BTNFerrari.setBounds(910, 250, 220, 220);

        BTNFord.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/marcas/ford.png"))); // NOI18N
        BTNFord.setBorderPainted(false);
        BTNFord.setContentAreaFilled(false);
        BTNFord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNFordActionPerformed(evt);
            }
        });
        getContentPane().add(BTNFord);
        BTNFord.setBounds(1160, 250, 220, 220);

        BTNPorsche.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/marcas/porsche.png"))); // NOI18N
        BTNPorsche.setBorderPainted(false);
        BTNPorsche.setContentAreaFilled(false);
        BTNPorsche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNPorscheActionPerformed(evt);
            }
        });
        getContentPane().add(BTNPorsche);
        BTNPorsche.setBounds(1160, 510, 220, 220);

        BTNToyota.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/marcas/toyota.png"))); // NOI18N
        BTNToyota.setBorderPainted(false);
        BTNToyota.setContentAreaFilled(false);
        BTNToyota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNToyotaActionPerformed(evt);
            }
        });
        getContentPane().add(BTNToyota);
        BTNToyota.setBounds(1410, 510, 220, 220);

        BTNMercedes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/marcas/mercedes.png"))); // NOI18N
        BTNMercedes.setBorderPainted(false);
        BTNMercedes.setContentAreaFilled(false);
        BTNMercedes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNMercedesActionPerformed(evt);
            }
        });
        getContentPane().add(BTNMercedes);
        BTNMercedes.setBounds(660, 510, 220, 220);

        BTNVolkswagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/marcas/volkswagen.png"))); // NOI18N
        BTNVolkswagen.setBorderPainted(false);
        BTNVolkswagen.setContentAreaFilled(false);
        BTNVolkswagen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNVolkswagenActionPerformed(evt);
            }
        });
        getContentPane().add(BTNVolkswagen);
        BTNVolkswagen.setBounds(910, 760, 220, 220);

        BTNHyundai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/marcas/hyundai.png"))); // NOI18N
        BTNHyundai.setBorderPainted(false);
        BTNHyundai.setContentAreaFilled(false);
        BTNHyundai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNHyundaiActionPerformed(evt);
            }
        });
        getContentPane().add(BTNHyundai);
        BTNHyundai.setBounds(400, 510, 220, 220);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/seta-esquerda.png"))); // NOI18N
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(130, 90, 120, 130);

        BTNOpel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/marcas/opel.png"))); // NOI18N
        BTNOpel.setBorderPainted(false);
        BTNOpel.setContentAreaFilled(false);
        BTNOpel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNOpelActionPerformed(evt);
            }
        });
        getContentPane().add(BTNOpel);
        BTNOpel.setBounds(910, 510, 220, 220);

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/background.jpg"))); // NOI18N
        getContentPane().add(background);
        background.setBounds(0, 0, 1920, 1080);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
           
        menu menu = new menu();
        menu.setVisible(true);
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void BTNAudiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNAudiActionPerformed
        // TODO add your handling code here:
        Marca("Audi");
    }//GEN-LAST:event_BTNAudiActionPerformed

    private void BTNBmwActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNBmwActionPerformed
        // TODO add your handling code here:
        Marca("BMW");
    }//GEN-LAST:event_BTNBmwActionPerformed

    private void BTNFerrariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNFerrariActionPerformed
        // TODO add your handling code here:
        Marca("Ferrari");
    }//GEN-LAST:event_BTNFerrariActionPerformed

    private void BTNFordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNFordActionPerformed
        // TODO add your handling code here:
        Marca("Ford");
    }//GEN-LAST:event_BTNFordActionPerformed

    private void BTNHondaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNHondaActionPerformed
        // TODO add your handling code here:
        Marca("Honda");
    }//GEN-LAST:event_BTNHondaActionPerformed

    private void BTNHyundaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNHyundaiActionPerformed
        // TODO add your handling code here:
        Marca("Hyundai");
    }//GEN-LAST:event_BTNHyundaiActionPerformed

    private void BTNMercedesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNMercedesActionPerformed
        // TODO add your handling code here:
        Marca("Mercedes");
    }//GEN-LAST:event_BTNMercedesActionPerformed

    private void BTNOpelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNOpelActionPerformed
        // TODO add your handling code here:
        Marca("Opel");
    }//GEN-LAST:event_BTNOpelActionPerformed

    private void BTNPorscheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNPorscheActionPerformed
        // TODO add your handling code here:
        Marca("Porsche");
    }//GEN-LAST:event_BTNPorscheActionPerformed

    private void BTNToyotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNToyotaActionPerformed
        // TODO add your handling code here:
        Marca("Toyota");
    }//GEN-LAST:event_BTNToyotaActionPerformed

    private void BTNVolkswagenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNVolkswagenActionPerformed
        // TODO add your handling code here:
        Marca("Volks");
    }//GEN-LAST:event_BTNVolkswagenActionPerformed

    private void BTNAvancarAudiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNAvancarAudiActionPerformed
        // TODO add your handling code here:
        if(contador <18){
            contador++;
            MoverModeloAudi();
        }
    }//GEN-LAST:event_BTNAvancarAudiActionPerformed

    private void BTNAnteriorAudiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNAnteriorAudiActionPerformed
        // TODO add your handling code here:
        if(contador > 1){
            contador--;
            MoverModeloAudi();
        }
    }//GEN-LAST:event_BTNAnteriorAudiActionPerformed

    private void ConcluirModeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConcluirModeloActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_ConcluirModeloActionPerformed

    private void Marca(String marca){
        BTNAudi.setVisible(false); BTNBmw.setVisible(false); BTNFerrari.setVisible(false); BTNFord.setVisible(false); BTNHonda.setVisible(false); BTNHyundai.setVisible(false); BTNMercedes.setVisible(false); BTNOpel.setVisible(false); BTNPorsche.setVisible(false); BTNToyota.setVisible(false); BTNVolkswagen.setVisible(false);
       
        
        switch(marca){
            case "Audi":
                Titulo.setText("Modelos "+marca);
                
                PAudi.setVisible(true);
                
            break;
            case "BMW":
                Titulo.setText("Modelos "+marca);
                
                
            break;
            case "Ferrari":
                Titulo.setText("Modelos "+marca);
            break;
            case "Ford":
                Titulo.setText("Modelos "+marca);
            break;
            case "Honda":
                Titulo.setText("Modelos "+marca);
            break;
            case "Hyundai":
                Titulo.setText("Modelos "+marca);
            break;
            case "Mercedes":
                Titulo.setText("Modelos "+marca);
            break;
            case "Opel":
                Titulo.setText("Modelos "+marca);
            break;
            case "Porsche":
                Titulo.setText("Modelos "+marca);
            break;
            case "Toyota":
                Titulo.setText("Modelos "+marca);
            break;
            case "Volks":
                Titulo.setText("Volkswagen");
            break;
        }
    }
    /**
     * @param args the command line arguments
     */
    private void MoverModeloAudi(){
        switch(contador){
            case 1: 
            NomeAudi.setText("Audi A1");
            ImagemAudi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MODELOS/audi/A1.png")));
            break;
            case 2:
            NomeAudi.setText("Audi A3");
            ImagemAudi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MODELOS/audi/A3.png")));
            break;
            case 3: 
            NomeAudi.setText("Audi A4");
            ImagemAudi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MODELOS/audi/A4.png")));
            break;
            case 4: 
            NomeAudi.setText("Audi A5");
            ImagemAudi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MODELOS/audi/A5.png")));
            break;
            case 5: 
            NomeAudi.setText("Audi A6");
            ImagemAudi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MODELOS/audi/A6.png")));
            break;
            case 6:
            NomeAudi.setText("Audi A7");
            ImagemAudi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MODELOS/audi/A7.png")));
            break;
            case 7: 
            NomeAudi.setText("Audi A8");
            ImagemAudi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MODELOS/audi/A8.png")));
            break;
            case 8: 
            NomeAudi.setText("Audi TT");
            ImagemAudi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MODELOS/audi/TT.png")));
            break;
            case 9: 
            NomeAudi.setText("Audi Q2");
            ImagemAudi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MODELOS/audi/Q2.png")));
            break;
            case 10: 
            NomeAudi.setText("Audi Q3");
            ImagemAudi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MODELOS/audi/Q3.png")));
            break;
            case 11: 
            NomeAudi.setText("Audi Q4");
            ImagemAudi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MODELOS/audi/Q4.png")));
            break;
            case 12: 
            NomeAudi.setText("Audi Q5");
            ImagemAudi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MODELOS/audi/Q5.png")));
            break;
            case 13: 
            NomeAudi.setText("Audi Q7");
            ImagemAudi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MODELOS/audi/Q7.png")));
            break;
            case 14: 
            NomeAudi.setText("Audi Q8");
            ImagemAudi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MODELOS/audi/Q8.png")));
            break;
            case 15: 
            NomeAudi.setText("Audi Q8 E-Tron");
            ImagemAudi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MODELOS/audi/Q8 E-TRON.png")));
            break;
            case 16: 
            NomeAudi.setText("Audi E-Tron GT");
            ImagemAudi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MODELOS/audi/E-TRON GT.png")));
            break;
            case 17: 
            NomeAudi.setText("Audi R8");
            ImagemAudi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MODELOS/audi/R8.png")));
            break;
        }
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(adicionar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(adicionar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(adicionar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(adicionar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new adicionar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNAnteriorAudi;
    private javax.swing.JToggleButton BTNAudi;
    private javax.swing.JButton BTNAvancarAudi;
    private javax.swing.JToggleButton BTNBmw;
    private javax.swing.JToggleButton BTNFerrari;
    private javax.swing.JToggleButton BTNFord;
    private javax.swing.JToggleButton BTNHonda;
    private javax.swing.JToggleButton BTNHyundai;
    private javax.swing.JToggleButton BTNMercedes;
    private javax.swing.JToggleButton BTNOpel;
    private javax.swing.JToggleButton BTNPorsche;
    private javax.swing.JToggleButton BTNToyota;
    private javax.swing.JToggleButton BTNVolkswagen;
    private javax.swing.JButton ConcluirModelo;
    private javax.swing.JLabel ImagemAudi;
    private javax.swing.JLabel NomeAudi;
    private java.awt.Panel PAudi;
    private javax.swing.JLabel Titulo;
    private javax.swing.JLabel background;
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
}
