/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mycar;

import java.awt.Color;
import static java.awt.Color.orange;
import static java.awt.Color.red;
import static java.awt.Color.yellow;
import java.util.HashMap;
import java.util.Map;

/**
 *
 * @author Shellby 56
 */
public class menu extends javax.swing.JFrame {

    /**
     * Creates new form menu
     */
    String TIdioma = "";
    String language = new String();
    int contaSair = 0, contaAdicionar = 0;
    
    Color padrao = new Color(255,153,0);
    Color atras = new Color(150,103,0);
    HashMap dict_pt ;
    HashMap dict_en ;
    
    
     
     
    public menu() {
        
        this.language="pt";
        dict_pt = new HashMap<String, String>();
        dict_en = new HashMap<String, String>();
        dict_pt.put("Add", "Adicionar"); dict_en.put("Add", "Add");
        dict_pt.put("Viz", "Visualizar"); dict_en.put("Viz", "Visualize");
        dict_pt.put("Language", "Idioma"); dict_en.put("Language", "Language");
        dict_pt.put("Leave", "Sair"); dict_en.put("Leave", "Leave App");
        dict_pt.put("Confirm", "Confirmar"); dict_en.put("Confirm", "Confirm");
        initComponents();
        
        
        
        
    //comecar desligado
    BTNPortugues.setVisible(false);
    BTNIngles.setVisible(false);
    ConcluirIdioma.setVisible(false);
    
    //
       
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BTNIdioma = new javax.swing.JButton();
        BTNSair = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        BTNVisualizar = new javax.swing.JButton();
        BTNAdicionar = new javax.swing.JButton();
        BTNIngles = new javax.swing.JButton();
        BTNPortugues = new javax.swing.JButton();
        ConcluirIdioma = new javax.swing.JButton();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MyGarage");
        setAlwaysOnTop(true);
        setMinimumSize(new java.awt.Dimension(1920, 1080));
        setUndecorated(true);
        getContentPane().setLayout(null);

        BTNIdioma.setFont(new java.awt.Font("Verdana Pro Cond Black", 0, 48)); // NOI18N
        BTNIdioma.setForeground(new java.awt.Color(255, 153, 0));
        BTNIdioma.setText("Idioma");
        BTNIdioma.setContentAreaFilled(false);
        BTNIdioma.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BTNIdioma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNIdiomaActionPerformed(evt);
            }
        });
        getContentPane().add(BTNIdioma);
        BTNIdioma.setBounds(370, 560, 320, 100);

        BTNSair.setFont(new java.awt.Font("Verdana Pro Cond Black", 0, 48)); // NOI18N
        BTNSair.setForeground(new java.awt.Color(255, 153, 0));
        BTNSair.setText("SAIR");
        BTNSair.setContentAreaFilled(false);
        BTNSair.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BTNSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNSairActionPerformed(evt);
            }
        });
        getContentPane().add(BTNSair);
        BTNSair.setBounds(370, 660, 260, 100);

        jLabel1.setBackground(javax.swing.UIManager.getDefaults().getColor("Actions.Yellow"));
        jLabel1.setFont(new java.awt.Font("Verdana Pro Cond Black", 0, 75)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 153, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("My Garage");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(90, 20, 1830, 140);

        BTNVisualizar.setFont(new java.awt.Font("Verdana Pro Cond Black", 0, 48)); // NOI18N
        BTNVisualizar.setForeground(new java.awt.Color(255, 153, 0));
        BTNVisualizar.setText("Visualizar");
        BTNVisualizar.setContentAreaFilled(false);
        BTNVisualizar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BTNVisualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNVisualizarActionPerformed(evt);
            }
        });
        getContentPane().add(BTNVisualizar);
        BTNVisualizar.setBounds(370, 460, 300, 100);

        BTNAdicionar.setFont(new java.awt.Font("Verdana Pro Cond Black", 0, 48)); // NOI18N
        BTNAdicionar.setForeground(new java.awt.Color(255, 153, 0));
        BTNAdicionar.setText("Adicionar");
        BTNAdicionar.setContentAreaFilled(false);
        BTNAdicionar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BTNAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNAdicionarActionPerformed(evt);
            }
        });
        getContentPane().add(BTNAdicionar);
        BTNAdicionar.setBounds(370, 360, 380, 100);

        BTNIngles.setFont(new java.awt.Font("Verdana Pro Cond Black", 0, 48)); // NOI18N
        BTNIngles.setForeground(new java.awt.Color(150, 103, 0));
        BTNIngles.setText("- Inglês");
        BTNIngles.setContentAreaFilled(false);
        BTNIngles.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BTNIngles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNInglesActionPerformed(evt);
            }
        });
        getContentPane().add(BTNIngles);
        BTNIngles.setBounds(820, 560, 300, 100);

        BTNPortugues.setFont(new java.awt.Font("Verdana Pro Cond Black", 0, 48)); // NOI18N
        BTNPortugues.setForeground(new java.awt.Color(255, 153, 0));
        BTNPortugues.setText("- Português");
        BTNPortugues.setContentAreaFilled(false);
        BTNPortugues.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BTNPortugues.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNPortuguesActionPerformed(evt);
            }
        });
        getContentPane().add(BTNPortugues);
        BTNPortugues.setBounds(820, 460, 330, 100);

        ConcluirIdioma.setFont(new java.awt.Font("Verdana Pro Cond Black", 0, 48)); // NOI18N
        ConcluirIdioma.setForeground(new java.awt.Color(255, 153, 0));
        ConcluirIdioma.setText("Confirmar");
        ConcluirIdioma.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(255, 153, 0)));
        ConcluirIdioma.setContentAreaFilled(false);
        ConcluirIdioma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConcluirIdiomaActionPerformed(evt);
            }
        });
        getContentPane().add(ConcluirIdioma);
        ConcluirIdioma.setBounds(1320, 690, 240, 70);

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/background.jpg"))); // NOI18N
        getContentPane().add(background);
        background.setBounds(0, 0, 1920, 1080);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    
    
    
    private void BTNSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNSairActionPerformed
        // TODO add your handling code here:
        contaAdicionar= 0;
        contaSair++;
        BTNIdioma.setForeground(atras);
        BTNVisualizar.setForeground(atras);
        BTNAdicionar.setForeground(atras);
        BTNSair.setForeground(padrao);
        BTNPortugues.setVisible(false);
        BTNIngles.setVisible(false);
        ConcluirIdioma.setVisible(false);
        if(contaSair==2){
        dispose();
        }
    }//GEN-LAST:event_BTNSairActionPerformed

    private void BTNIdiomaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNIdiomaActionPerformed
        // TODO add your handling code here:
        contaAdicionar= 0;
        contaSair = 0;
        BTNSair.setForeground(atras);
        BTNVisualizar.setForeground(atras);
        BTNAdicionar.setForeground(atras);
        BTNIdioma.setForeground(padrao);
        BTNPortugues.setVisible(true);
        BTNIngles.setVisible(true);
        ConcluirIdioma.setVisible(true);
        
        
    }//GEN-LAST:event_BTNIdiomaActionPerformed

    private void BTNVisualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNVisualizarActionPerformed
        // TODO add your handling code here:
        contaAdicionar= 0;
        contaSair = 0;
        BTNSair.setForeground(atras);
        BTNIdioma.setForeground(atras);
        BTNAdicionar.setForeground(atras);
        BTNVisualizar.setForeground(padrao);
        BTNPortugues.setVisible(false);
        BTNIngles.setVisible(false);
        ConcluirIdioma.setVisible(false);
    }//GEN-LAST:event_BTNVisualizarActionPerformed

    private void BTNAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNAdicionarActionPerformed
        // TODO add your handling code here:
        contaAdicionar++;
        contaSair = 0;
        BTNSair.setForeground(atras);
        BTNIdioma.setForeground(atras);
        BTNVisualizar.setForeground(atras);
        BTNAdicionar.setForeground(padrao);
        BTNPortugues.setVisible(false);
        BTNIngles.setVisible(false);
        ConcluirIdioma.setVisible(false);
        
        if(contaAdicionar==2){
           
        this.dispose();
           
        adicionar adicionar = new adicionar();
        adicionar.setVisible(true);
        
        }
        
        
    }//GEN-LAST:event_BTNAdicionarActionPerformed

    private void BTNInglesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNInglesActionPerformed
        // TODO add your handling code here:
        BTNIngles.setForeground(padrao);
        BTNPortugues.setForeground(atras);
        this.language = "ING";
    }//GEN-LAST:event_BTNInglesActionPerformed

    private void BTNPortuguesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNPortuguesActionPerformed
        // TODO add your handling code here:
        BTNIngles.setForeground(atras);
        BTNPortugues.setForeground(padrao);
        this.language = "PT";
    }//GEN-LAST:event_BTNPortuguesActionPerformed

    private void ConcluirIdiomaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConcluirIdiomaActionPerformed
        // TODO add your handling code here:
        mudarIdioma();
        

        
        
        BTNPortugues.setVisible(false);
        BTNIngles.setVisible(false);
        ConcluirIdioma.setVisible(false);
        BTNSair.setForeground(padrao);
        BTNIdioma.setForeground(padrao);
        BTNVisualizar.setForeground(padrao);
        BTNAdicionar.setForeground(padrao);
    }//GEN-LAST:event_ConcluirIdiomaActionPerformed


    
    
    private void mudarIdioma(){  
        HashMap dict = new HashMap<String, String>();
        switch(this.language){
            case ("PT") -> dict = this.dict_pt;
            case("ING") -> dict = this.dict_en;
        }
       
        
        BTNAdicionar.setText((String)dict.get("Add"));
        BTNVisualizar.setText((String)dict.get("Viz"));
        BTNIdioma.setText((String)dict.get("Language"));
        BTNSair.setText((String)dict.get("Leave"));
        BTNPortugues.setText("- Portuguese");
        BTNIngles.setText("- English");
        ConcluirIdioma.setText((String)dict.get("Confirm"));
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menu().setVisible(true);
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNAdicionar;
    private javax.swing.JButton BTNIdioma;
    private javax.swing.JButton BTNIngles;
    private javax.swing.JButton BTNPortugues;
    private javax.swing.JButton BTNSair;
    private javax.swing.JButton BTNVisualizar;
    private javax.swing.JButton ConcluirIdioma;
    private javax.swing.JLabel background;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
